
"Appearance
syntax enable 
set background=dark 
colorscheme solarized 
set guifont=Inconsolata\ Medium\ 12


"General Settings
filetype plugin on
filetype indent on
set tabstop=4
set shiftwidth=4
set expandtab

"Operation"
set backspace=eol,start,indent
set ffs=unix
set noerrorbells
set novisualbell
set t_vb=
set nocompatible
set pastetoggle=<F2>

"Turn off Scroll Bars
set guioptions-=L
set guioptions-=r
set guioptions-=b

"Automatically even split windows
autocmd VimResized * wincmd =
" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

noremap <F8> :call CompileRun()<CR>
function! CompileRun()
    if &filetype == 'c'
        :w
        :!gcc % -g -o %< && ./%<
    elseif &filetype == 'cpp'
        :w
        :!g++ -g -std=c++11 % -o %< && ./%<
    else
        :echo "Nothing to do with this filetype"
    endif
endfunction
