call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
"filetype plugin on
set backspace=eol,start,indent

"Searching
set ignorecase
set smartcase
set hlsearch
set incsearch


set showmatch
set noerrorbells
set novisualbell
set t_vb=

syntax enable
colorscheme darkspectrum
set ffs=unix
set gfn=Droid\ Sans\ Mono\ 11
set nocompatible
set columns=80


"General Settings"
set tabstop=8
set laststatus=2
set shiftwidth=8
set autoread    "Reload files changed outside vim"
set showmode    "Show current mode down at the bottom"
set textwidth=80


"Fancy Stuff"
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
match Todo /\s\+$/
