" Vundle Stuff"
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.Vim
call vundle#begin()

"Plugins"
Plugin 'VundleVim/Vundle.Vim'
Plugin 'vim-scripts/taglist.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'pearofducks/ansible-vim'
Plugin 'fatih/vim-go'
Plugin 'NoahTheDuke/vim-just'

"Colors"
Plugin 'altercation/vim-colors-solarized'

"End of Vundle Stuff"
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

"Apperance"
set t_Co=256
set background=dark
colorscheme solarized
set gfn=Inconsolata\ Medium\ 12
syntax on

" lightline Theme"
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }

"Searching"
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set autochdir



"General Settings"
set number
set laststatus=2
set autoread    "Reload files changed outside vim"
set showmode    "Show current mode down at the bottom"
set modeline
set tags=./tags,tags;
autocmd FileType python setlocal tabstop=4 shiftwidth=4 expandtab
autocmd FileType ruby   setlocal tabstop=2 shiftwidth=2 expandtab
autocmd FileType c,c++ setlocal tabstop=4 shiftwidth=4 noexpandtab
autocmd FileType markdown setlocal spell spelllang=en_us textwidth=79 formatoptions+=ta formatoptions-=l
autocmd FileType markdown highlight SpellBad ctermfg=009 ctermbg=011 guifg=#ff0000 guibg=#ffff00 
autocmd FileType yml,yaml setlocal tabstop=2 sts=2 sw=2 expandtab number list listchars=tab:>-,eol:¬,trail:⋅,multispace:⋅⋅⋅\|

"Operation"
set backspace=eol,start,indent
set ffs=unix
set noerrorbells
set novisualbell
set t_vb=
set nocompatible
set pastetoggle=<F2>
set ttyfast


"Fancy Stuff"
"set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
match Todo /\s\+$/
autocmd VimResized * wincmd =

"Toggle Taglist"
nnoremap <Leader>t :TlistToggle<CR>

" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

noremap <F8> :call CompileRun()<CR>
function! CompileRun()
    if &filetype == 'c'
        :w
        :!gcc % -g -o %< && ./%<
    elseif &filetype == 'cpp'
        :w
        :!g++ -std=c++14 % -o %< && ./%<
    else
        :echo "Nothing to do with this filetype"
    endif
endfunction

